version: '3.8'
services:
  db:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/example-data.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
      - ./db/pgadmin-servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data:
